FROM openjdk:8-jre-alpine
COPY target/auldfellas-0.0.1-jar-with-dependencies.jar /auldfellas-0.0.1-jar-with-dependencies.jar
CMD sleep 10 && /usr/bin/java -jar /auldfellas-0.0.1-jar-with-dependencies.jar 

# FROM openjdk:8-jre-alpine

# ENV SERVER_HOST localhost

# COPY target/auldfellas-0.0.1-jar-with-dependencies.jar /auldfellas-0.0.1-jar-with-dependencies.jar

# CMD ["/bin/sh", "-c", "sleep 10 && /usr/bin/java -cp /auldfellas-0.0.1-jar-with-dependencies.jar auldfellasMain ${SERVER_HOST}"]

