version: "3.6"
services:
  broker:
    build: broker
    depends_on:
      - auldfellas
      - girlsallowed
      - dodgygeezers
    ports:
      - 8083:8083
  auldfellas:
    build: auldfellas
    ports:
      - 8080:8080
  girlsallowed:
    build: girlsallowed
    ports:
      - 8081:8081
  dodgygeezers:
    build: dodgygeezers
    ports:
      - 8082:8082
