version: "3"

services:
  auldfellas:
    build:
      context: ./auldfellas
      dockerfile: Dockerfile
    ports:
      - "9001:9001"

  dodgygeezers:
    build:
      context: ./dodgygeezers
      dockerfile: Dockerfile
    ports:
      - "9002:9002"

  girlsallowed:
    build:
      context: ./girlsallowed
      dockerfile: Dockerfile
    ports:
      - "9003:9003"

  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - auldfellas
      - girlsallowed
      - dodgygeezers
# version: "2"

# services:
#   broker:
#     build: broker
#     ports:
#       - "9000:9000" # Expose the broker's port

#   auldfellas:
#     build: auldfellas
#     environment:
#       SERVER_HOST: broker
#     depends_on:
#       - broker

#   girlsallowed:
#     build: girlsallowed
#     environment:
#       SERVER_HOST: broker
#     depends_on:
#       - broker

#   dodgygeezers:
#     build: dodgygeezers
#     environment:
#       SERVER_HOST: broker
#     depends_on:
#       - broker
