version: "3.6"

services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
  broker:
    build: ./broker
    container_name: broker
    depends_on:
      - activemq
    environment:
      - BROKER_HOST=activemq
  auldfellas:
    build: ./auldfellas
    container_name: auldfellas
    depends_on:
      - activemq
    environment:
      - BROKER_HOST=activemq
  dodgydrivers:
    build: ./dodgygeezers
    container_name: dodgygeezers
    depends_on:
      - activemq
    environment:
      - BROKER_HOST=activemq
  girlpower:
    build: ./girlsallowed
    container_name: girlsallowed
    depends_on:
      - activemq
    environment:
      - BROKER_HOST=activemq
